### ISSUE TITLE
undefined Query_Builder_Select::get()

### ISSUE THREAD

**Issue by marisajoang** [OkveeNet/fuel-start#6]
Hi try make it test project with your awesome fuel-start, but I have problem when follow your style script like this : 
 <code>
public static function listProducts($option = array())
  {
    // get total products of current visitor
    //$query = static::query();
    $query = \DB::select('catduty.catduty_name','vehicle.vehicle_name','catpart.catpart_name','category.category_id','category.category_name','products.products_id','products.products_name','products.products_price','products.products_subtitute_code')
               ->from('products')
               ->join('category')->on('products.category_id','=','category.category_id')
               ->join('catpart')->on('category.catpart_id','=','catpart.catpart_id')
               ->join('vehicle')->on('catpart.vehicle_id','=','vehicle.vehicle_id')
               ->join('catduty')->on('catduty.catduty_id','=','vehicle.catduty_id');

    // search
    if (isset($option['search']) && $option['search'] != null) {
        $search = $option['search'];
        $query->where_open()
              ->where('catduty.catduty_name', 'LIKE', '%' . \Security::htmlentities($search) . '%')
              ->or_where('vehicle.vehicle_name', 'LIKE', '%' . \Security::htmlentities($search) . '%')
              ->or_where('catpart.catpart_name', 'LIKE', '%' . \Security::htmlentities($search) . '%')
              ->or_where('category.category_name', 'LIKE', '%' . \Security::htmlentities($search) . '%')
              ->or_where('products.products_id', 'LIKE', '%' . $search . '%')
              ->or_where('products.products_code', 'LIKE', '%' . $search . '%')
              ->or_where('products.products_name', 'LIKE', '%' . \Security::htmlentities($search) . '%')
              ->or_where('products.products_price', 'LIKE', '%' . $search . '%')
              ->or_where('products.products_stock', 'LIKE', '%' . $search . '%')
              ->or_where('products.products_subtitute_code', 'LIKE', '%' . $search . '%')
              ->where_close();
        unset($search);
    }
    //$output['total'] = $query->count();
    // sort and order
    $allowed_orders = array('catduty.catduty_name','vehicle.vehicle_name','catpart.catpart_name','category.category_name','products.products_id', 'products.products_code', 'products.products_name', 'products.products_price', 'products.products_stock', 'products.products_subtitute_code','category.category_id');
    if (!isset($option['orders']) || (isset($option['orders']) && !in_array($option['orders'], $allowed_orders))) {
        $option['orders'] = 'products.products_id';
    }
    unset($allowed_orders);
    if (!isset($option['sort'])) {
        $option['sort'] = 'ASC';
    }
    // offset and limit
    if (!isset($option['offset'])) {
        $option['offset'] = 0;
    }
    if (!isset($option['limit'])) {
        if (isset($option['list_for']) && $option['list_for'] == 'all') {
            $option['limit'] = \Model_Config::getval('content_items_perpage');
        } else {
            $option['limit'] = \Model_Config::getval('content_items_perpage');
        }
    }
    // get the results from sort, order, offset, limit.
    $output['items'] = $query->order_by($option['orders'], $option['sort'])->offset($option['offset'])->limit($option['limit'])->get();
    unset($query);
    return $output;
  }// listProducts

</code>

the $output['items'] undefined method for query builder, can you help me? to solve this.. 
Thanks In Advance

**Comment by ve3** [comment]
You cannot use `get()` while using \DB class.

The `get()` is for ORM.

Please change it to `execute()`.
For more information please see FuelPHP's document.

**Comment by marisajoang** [comment]
I try <code>execute()</code> before. but in controller I've got error "Undefined index: total" using pagination your style script.
yes, I've problem follow using query join with ORM in FuelPHP's document, so I using \DB class.
and that's why I didn't get solve. 
any suggest it can solve with your style script ? 
I really thanks to you fast response.
Thanks In Advance

**Comment by ve3** [comment]
You have commented the total array index.
``
//$output['total'] = $query->count();
``

If you want to use 'total' array key, please un-comment the code. The `count()` is for ORM if you want to count total please use `count($query->execute())` for \DB class.

Before you call any array key please make sure that there is that array key in the result. To do this, use `array_key_exists()` or `isset()` to check.
