### ISSUE TITLE
Default Admin Password

### ISSUE THREAD

**Issue by codingarrow** [OkveeNet/fuel-start#7]
What is the default admin password for this?   E-mail It's not working on forgot password...

INSERT INTO `ws_accounts` (`account_id`, `account_username`, `account_email`, `account_salt`, `account_password`, `account_display_name`, `account_firstname`, `account_middlename`, `account_lastname`, `account_birthdate`, `account_avatar`, `account_signature`, `account_timezone`, `account_language`, `account_create`, `account_create_gmt`, `account_last_login`, `account_last_login_gmt`, `account_status`, `account_status_text`, `account_new_email`, `account_new_password`, `account_confirm_code`, `account_confirm_code_since`) VALUES
(0, 'Guest', 'none@localhost', NULL, NULL, 'Guest', NULL, NULL, NULL, NULL, NULL, NULL, '(UTC+07:00) Bangkok', NULL, 1387121127, 1387095927, NULL, NULL, 0, 'This account is for guest actions.', NULL, NULL, NULL, NULL),
(1, 'admin', 'admin????', NULL, '$2a$12$mPxupqGhPePgQAPvCpVUqekNfh.cAVusmgQyz1ZTfkcVLN0GBT7am', 'admin', NULL, NULL, NULL, NULL, NULL, NULL, '(UTC+07:00) Bangkok', NULL, 1387121127, 1387095927, 1429120159, 1429094959, 1, NULL, NULL, NULL, NULL, NULL);

**Comment by ve3** [comment]
please read the installation document in [Wiki](https://github.com/OkveeNet/fuel-start/wiki/v1-Install-Fuel-Start).

Email not working because it is admin????. You have to manually change it in the database using phpmyadmin or something like that.
